### ISSUE TITLE
Is it possible to build supervisor for py3k

### ISSUE THREAD

**Issue by schierkolk** [conda-forge/supervisor-feedstock#12]
Currently the package only support python 2.x. Is it possible to build supervisor for py3k ?

**Comment by sodre** [comment]
Not at the moment because supervisord 3.x only supports Python 2. This is scheduled to be fixed in supervisord 4.

cf: 
  - [Supervisord Documentation](
http://supervisord.org/introduction.html#platform-requirements)
  - [stackoverflow](https://stackoverflow.com/questions/19796883/supervisord-for-python-3)

**Comment by sodre** [comment]
One viable workaround:
  - Install supervisord in a python 2.7 conda environment.
  - Install your own code in a separate python 3 conda environment.
  - Use `conda exec`(https://github.com/conda-forge/conda-exec-feedstock), or possibly `conda run`( conda/conda#7320)  to let supervisord start and stop your Python 3.x service. 

If you need more details on this possible workaround let me know.
